name: Build ios
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ ios-workflow ]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Getting the Repository
        uses: actions/checkout@v2
      - name: Installing node
        uses: actions/setup-node@v1
      - name: Installing react-native-cli
        run: |
           npm install -g react-native-cli
      - name: Install npm dependencies 
        run: |
          cd App && npm install --legacy-peer-deps
      - name: Decode config.json
        env:
          CONFIG_SECRET: ${{ secrets.CONFIG_SECRET}}
        run: echo $CONFIG_SECRET > App/config.json
      - name: Decode google-services.plist
        env: 
          IOS_DEV_SECRET: ${{secrets.IOS_DEV_SECRET}}
        run: echo $IOS_DEV_SECRET > App/ios/GoogleServices-Info.plist
        
      - name: BUNDLE Ios-Release
        run: |
          cd App && npm react-native bundle --platform ios --dev false --entry-file index.js --bundle-output ios/main.jsbundle --assets-dest ios
          
      - name: install Pods
        run: cd App && cd ios && pod install
      
      
      
    
      
      
  
          
